spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5435/niger_services
spring.datasource.username=niger_services
spring.datasource.password=niger_services
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

management.endpoints.web.exposure.include=health,info